version: '3'

services:

  subquery-node-rmrk-indexer:
    image: onfinality/subql-node:v1.10.2
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: p>postgres123#2022Web3Go
      DB_DATABASE: prod-rmrk
      DB_HOST: web3go-pg.cco8evagtdwc.ap-southeast-1.rds.amazonaws.com
      DB_PORT: 5432
    volumes:
      - ./:/app
    command:
      - -f=/app
      - --db-schema=public
      - --log-level debug
      - --batch-size=10

